# corresponds to DatasetConfig
dataset:
  dataset_type: "huggingface"
  dataset_loc: "zpn/uniref50"
  train_sample_size: 100
  sequence_column_name: "sequence"
  max_sequence_length: 10

# corresponds to TrainingArgsConfig
training_args:
  output_dir: "checkpoints/toy"
  max_steps: 1
  num_train_epochs: 1
  learning_rate: 0.1
  weight_decay: 0.1
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  save_steps: 1
  report_to: "none"
  label_names:
    - 'labels'
  no_cuda: false

# corresponds to TokenizerConfig
tokenizer:
  tokenizer_type: "APT"

# corresponds to NNModelConfig
model:
  nn_model_type: "APT"
  nn_model_config_args:
    attention_mode: "APT"
    position_embedding: "learned"
  pretrained_checkpoint: null

# corresponds to DataCollatorConfig
data_collator:
  data_collator_type: "default"
