# corresponds to DatasetConfig
dataset:
  dataset_type: "huggingface"
  dataset_loc: "zpn/uniref50"
  subsample_size: 1000
  split_seed: 2
  val_size: 10
  test_size: 10
  sequence_column_name: "sequence"
  max_sequence_length: 10
  do_curriculum_learning: false

# corresponds to HuggingFace's TrainingArguments
training_arguments:
  output_dir: "checkpoints/toy_hf"
  num_train_epochs: 2
  learning_rate: 0.1
  weight_decay: 0.1
  save_strategy: "epoch"
  per_device_train_batch_size: 10
  save_steps: 5
  evaluation_strategy: "steps"
  eval_steps: 5
  report_to: "wandb"
  label_names:
    - 'labels'
  no_cuda: false
  ddp_find_unused_parameters: false

# corresponds to WandBConfig
wandb:
  name: "toy_hf"
  dir: "wandb_files/"

# corresponds to TokenizerConfig
tokenizer:
  tokenizer_type: "APT"

# corresponds to NNModelConfig
model:
  nn_model_type: "APT"
  nn_model_config_args:
    position_embedding: "learned"
    rope_scaling_factor: 1.0
    rope_theta: 10000
    max_sequence_length: 10
  pretrained_checkpoint: null

# corresponds to DataCollatorConfig
data_collator:
  data_collator_type: "default"
